---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - name: Create cinder service
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_service"
      service_name: "cinder"
      service_type: "volume"
      description: "OpenStack Block Storage"
      endpoint: "https://{{ keystone_fqdn }}:{{keystone_admin_port}}/v3"
      insecure: yes

  - name: Create cinderv2 service
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_service"
      service_name: "cinderv2"
      service_type: "volumev2"
      description: "OpenStack Block Storage"
      endpoint: "https://{{ keystone_fqdn }}:{{keystone_admin_port}}/v3"
      insecure: yes

  - name: Create cinder endpoints
    delegate_to: "{{ groups['openstack_identity'][0] }}"
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_endpoint"
      region_name: "RegionOne"
      service_name: "{{ item.name }}"
      service_type: "{{ item.type }}"
      endpoint_list:
        - url: "{{ item.public_url }}"
          interface: "public"
        - url: "{{ item.internal_url }}"
          interface: "internal"
        - url: "{{ item.admin_url }}"
          interface: "admin"
      endpoint: "https://{{ keystone_fqdn }}:{{keystone_admin_port}}/v3"
      insecure: yes
    with_items:
      - name: cinder
        type: volume
        public_url: "http://{{ groups['openstack_block_storage_controller'][0] }}:8776/v1/%(tenant_id)s"
        internal_url: "http://{{ groups['openstack_block_storage_controller'][0] }}:8776/v1/%(tenant_id)s"
        admin_url: "http://{{ groups['openstack_block_storage_controller'][0] }}:8776/v1/%(tenant_id)s"
      - name: cinderv2
        type: volumev2
        public_url: "http://{{ groups['openstack_block_storage_controller'][0] }}:8776/v2/%(tenant_id)s"
        internal_url: "http://{{ groups['openstack_block_storage_controller'][0] }}:8776/v2/%(tenant_id)s"
        admin_url: "http://{{ groups['openstack_block_storage_controller'][0] }}:8776/v2/%(tenant_id)s"
