---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - include: cinder_db_setup.yml
  - include: cinder_db_sync.yml
  - include: cinder_service_entities.yml
  - include: cinder_project_access.yml

  - name: Retrieve the certificate
    delegate_to: "{{ groups['openstack_identity'][0] }}"
    synchronize: src=/etc/keystone/ssl/cacert.pem dest=/etc/cinder

  - name: Ensure proper permissions of the certificate
    file: path=/etc/cinder/cacert.pem owner=cinder group=cinder mode=400

  - include: cinder_certificates.yml

  - name: Create /etc/nginx directory
    file: path=/etc/nginx state=directory

  - name: Create cinder configuration for nginx
    template: dest=/etc/nginx/cinder.conf src=nginx-cinder.conf.j2
    notify:
      - restart cinder controller
      - restart nginx

  - name: Ensure Cinder is running
    service: name={{ item }} enabled=yes state=started
    with_items:
      - nginx
      - uwsgi@cinder-api.socket

  - meta: flush_handlers
